// <auto-generated />
using Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Db.Migrations
{
    [DbContext(typeof(BloggingContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("Db.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Url")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("url")
                        .UseCollation("CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_R_BLOG");

                    b.ToTable("r_blog", (string)null);
                });

            modelBuilder.Entity("Db.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_blog");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content")
                        .UseCollation("CI_AS");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("title")
                        .UseCollation("CI_AS");

                    b.HasKey("Id")
                        .HasName("PK_R_POST");

                    b.HasIndex("BlogId");

                    b.ToTable("r_post", (string)null);
                });

            modelBuilder.Entity("Db.Post", b =>
                {
                    b.HasOne("Db.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_R_POST_R_BLOG");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("Db.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
